[package]
authors = ["Heiya <morooka.akira.inon29@gmail.com>"]
edition = "2018"
name = "nokogiri"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
