[package]
edition = "2021"
name = "mandelbrot"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
image = "0.13.0"
num = "0.4"
