[package]
edition = "2021"
name = "monkey"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"
once_cell = "1.12.0"
users = "0.11.0"
